// <auto-generated />
using MVCX1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCX1.Migrations
{
    [DbContext(typeof(PlayDB))]
    [Migration("20210722085501_suya")]
    partial class suya
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCX1.Models.Players", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Defence")
                        .HasColumnType("int");

                    b.Property<int>("Dribble")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Passing")
                        .HasColumnType("int");

                    b.Property<int>("Shoot")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("UserX");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Defence = 99,
                            Dribble = 96,
                            Name = "Alves",
                            Passing = 98,
                            Shoot = 90
                        },
                        new
                        {
                            ID = 2,
                            Defence = 60,
                            Dribble = 99,
                            Name = "Messi",
                            Passing = 97,
                            Shoot = 99
                        },
                        new
                        {
                            ID = 3,
                            Defence = 93,
                            Dribble = 96,
                            Name = "XAVI",
                            Passing = 99,
                            Shoot = 92
                        },
                        new
                        {
                            ID = 4,
                            Defence = 85,
                            Dribble = 98,
                            Name = "Iniesta",
                            Passing = 98,
                            Shoot = 99
                        },
                        new
                        {
                            ID = 5,
                            Defence = 75,
                            Dribble = 97,
                            Name = "Suarez",
                            Passing = 90,
                            Shoot = 99
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
